version: '3.9'  

services:

  mysql:
    image: mysql:8.0  
    restart: unless-stopped  
    environment:
      MYSQL_DATABASE: smartera-management-system
      MYSQL_PASSWORD: Y1lmaz090909y
      MYSQL_ROOT_PASSWORD: Y1lmaz090909y
    volumes:
      - mysql_data:/var/lib/mysql 
    ports:
      - 3306:3306  
    expose:
      - "3306"

  customer-service:
    build: ./customer-service 
    restart: no
    depends_on:
      - mysql  
    ports:
      - "3310:3306"


  order-service:
    build: ./order-service  
    restart: no  
    depends_on:
      - mysql  
    ports:
      - "3311:3306"

  ui:
    build: ./ui 
    restart: no
    ports:
      - "4200:4200"
    volumes:
      - ./ui:/app 


volumes:
  mysql_data: {}
