version: '3.9'

networks:
  my-network:

services:
  # MySQL service

  mysql:
    image: mysql:8.0
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: smartera-management-system
      MYSQL_USER: root
      MYSQL_PASSWORD: Y1lmaz090909y
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"

    networks:
      - my-network

  # Backend services (customer-service and order-service)
  customer-service:
    build: ./customer-service
    restart: no
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    networks:
      - my-network

  order-service:
    build: ./order-service
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      - "8081:8081"
    networks:
      - my-network

  # Angular application
  ui:
    build: ./ui
    restart: no
    ports:
      - "4200:4200"
    volumes:
      - ./ui:/app
    networks:
      - my-network

# Volume definition for persistent data
volumes:
  mysql_data: {}
