version: "3"

services:
    angular:
     build:
      context:
       dockerfile: Dockerfile.angular
      ports:
      - "80:80"
    db:
      image: mysql:5.7
      restart: always
      environment:
        MYSQL_DATABASE: 'smartera-management-system'
        MYSQL_USER: 'root'
        MYSQL_PASSWORD: 'Y1lmaz090909y'
        MYSQL_ROOT_PASSWORD: 'Y1lmaz090909y'
      ports:
        - '3306:3306'
      expose:
        - '3306'
      volumes:
        - my-db:/var/lib/mysql
  customer-service:
    build: ./customer-service
    ports:
      - "8080:8080"
  order-service:
    build: ./order-service
    ports:
      - "8081:8081"
    depends_on:
      - mysql