

INSERT INTO product (product_name, quantity) VALUES ('Silgi', 10);
INSERT INTO product (product_name, quantity) VALUES ('Kurşun Kalem', 2);
INSERT INTO product (product_name, quantity) VALUES ('Dolma Kalem', 5);
INSERT INTO product (product_name, quantity) VALUES ('Ajanda', 15);
INSERT INTO product (product_name, quantity) VALUES ('Rulo Bant', 4);
INSERT INTO product (product_name, quantity) VALUES ('Zımba', 6);
INSERT INTO product (product_name, quantity) VALUES ('Akıllı Telefon', 1500);
INSERT INTO product (product_name, quantity) VALUES ('Laptop', 3000);
INSERT INTO product (product_name, quantity) VALUES ('Tablet', 800);
INSERT INTO product (product_name, quantity) VALUES ('Kablosuz Fare', 50);
INSERT INTO product (product_name, quantity) VALUES ('Bluetooth Kulaklık', 100);
INSERT INTO product (product_name, quantity) VALUES ('Harici Sabit Disk', 200);
INSERT INTO product (product_name, quantity) VALUES ('USB Bellek', 20);
INSERT INTO product (product_name, quantity) VALUES ('Mouse Pad', 10);
INSERT INTO product (product_name, quantity) VALUES ('Ekran Koruyucu Filmi', 15);
INSERT INTO product (product_name, quantity) VALUES ('HDMI Kablosu', 25);
INSERT INTO product (product_name, quantity) VALUES ('Elektrikli Süpürge', 500);
INSERT INTO product (product_name, quantity) VALUES ('Bulaşık Makinesi', 1000);
INSERT INTO product (product_name, quantity) VALUES ('Mikrodalga Fırın', 300);
INSERT INTO product (product_name, quantity) VALUES ('Blender', 50);
INSERT INTO product (product_name, quantity) VALUES ('Tost Makinesi', 40);
INSERT INTO product (product_name, quantity) VALUES ('Su Isıtıcı', 30);
INSERT INTO product (product_name, quantity) VALUES ('Elektrikli Çaydanlık', 25);
INSERT INTO product (product_name, quantity) VALUES ('Ütü', 60);
INSERT INTO product (product_name, quantity) VALUES ('Elektrikli Mutfak Robotu', 200);
INSERT INTO product (product_name, quantity) VALUES ('Kahve Makinesi', 80);
INSERT INTO product (product_name, quantity) VALUES ('Araba Aküsü', 300);
INSERT INTO product (product_name, quantity) VALUES ('Fren Diski', 150);
INSERT INTO product (product_name, quantity) VALUES ('Yağ Filtresi', 20);
INSERT INTO product (product_name, quantity) VALUES ('Radyatör', 200);
INSERT INTO product (product_name, quantity) VALUES ('Ayna', 50);
INSERT INTO product (product_name, quantity) VALUES ('Far Ampulü', 10);
INSERT INTO product (product_name, quantity) VALUES ('Jant', 100);
INSERT INTO product (product_name, quantity) VALUES ('Bujiler', 30);
INSERT INTO product (product_name, quantity) VALUES ('Direksiyon Simidi', 80);
INSERT INTO product (product_name, quantity) VALUES ('Motor Yağı', 40);
INSERT INTO product (product_name, quantity) VALUES ('Fındık', 15);
INSERT INTO product (product_name, quantity) VALUES ('Mısır', 10);
INSERT INTO product (product_name, quantity) VALUES ('Buğday', 12);
INSERT INTO product (product_name, quantity) VALUES ('Pamuk', 18);
INSERT INTO product (product_name, quantity) VALUES ('Üzüm', 8);
INSERT INTO product (product_name, quantity) VALUES ('Elma', 6);
INSERT INTO product (product_name, quantity) VALUES ('Domates', 4);
INSERT INTO product (product_name, quantity) VALUES ('Salatalık', 3);
INSERT INTO product (product_name, quantity) VALUES ('Patates', 5);
INSERT INTO product (product_name, quantity) VALUES ('Havuç', 3);
INSERT INTO product (product_name, quantity) VALUES ('Kolye', 50);
INSERT INTO product (product_name, quantity) VALUES ('Bilezik', 80);
INSERT INTO product (product_name, quantity) VALUES ('Yüzük', 30);
INSERT INTO product (product_name, quantity) VALUES ('Küpe', 40);
INSERT INTO product (product_name, quantity) VALUES ('Saat', 100);
INSERT INTO product (product_name, quantity) VALUES ('Broş', 20);
INSERT INTO product (product_name, quantity) VALUES ('Tişört', 25);
INSERT INTO product (product_name, quantity) VALUES ('Pantolon', 40);
INSERT INTO product (product_name, quantity) VALUES ('Gömlek', 35);
INSERT INTO product (product_name, quantity) VALUES ('Kazak', 50);
INSERT INTO product (product_name, quantity) VALUES ('Etek', 30);
INSERT INTO product (product_name, quantity) VALUES ('Ceket', 60);
INSERT INTO product (product_name, quantity) VALUES ('Şampuan', 15);
INSERT INTO product (product_name, quantity) VALUES ('Diş Fırçası', 5);
INSERT INTO product (product_name, quantity) VALUES ('Vitamin Takviyesi', 20);
INSERT INTO product (product_name, quantity) VALUES ('Losyon', 25);
INSERT INTO product (product_name, quantity) VALUES ('Nemlendirici Krem', 30);
INSERT INTO product (product_name, quantity) VALUES ('Ağız Gargarası', 10);
INSERT INTO product (product_name, quantity) VALUES ('Süpürge', 150);
INSERT INTO product (product_name, quantity) VALUES ('Bulaşık Deterjanı', 20);
INSERT INTO product (product_name, quantity) VALUES ('Cam Temizleyici', 10);
INSERT INTO product (product_name, quantity) VALUES ('Tuvalet Fırçası', 8);
INSERT INTO product (product_name, quantity) VALUES ('Sıvı Sabun', 5);
INSERT INTO product (product_name, quantity) VALUES ('Temizlik Bezi', 3);
INSERT INTO product (product_name, quantity) VALUES ('Tuğla', 2);
INSERT INTO product (product_name, quantity) VALUES ('Çimento', 10);
INSERT INTO product (product_name, quantity) VALUES ('Kum', 5);
INSERT INTO product (product_name, quantity) VALUES ('Demir Çubuk', 15);
INSERT INTO product (product_name, quantity) VALUES ('Kireç', 8);
INSERT INTO product (product_name, quantity) VALUES ('Marley', 20);
INSERT INTO product (product_name, quantity) VALUES ('Kalem seti', 15);
INSERT INTO product (product_name, quantity) VALUES ('Kalem Seti', 15);
INSERT INTO product (product_name, quantity) VALUES ('Kalem Seti', 15);
INSERT INTO product (product_name, quantity) VALUES ('Dosya', 5);



