#version: '3.8'
#
#services:
#  mysql:
#    image: mysql:latest
#    restart: always
#    environment:
#      MYSQL_ROOT_PASSWORD: Y1lmaz090909y
#      MYSQL_DATABASE: smartera-management-system
#    ports:
#      - "3306:3306"
#
#  order-service:
#    image: your-order-service-image:latest
#    ports:
#      - "8081:8081"
#    depends_on:
#      - mysql
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/smartera-management-system
#      SPRING_DATASOURCE_USERNAME: root
#      SPRING_DATASOURCE_PASSWORD: Y1lmaz090909y
#      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect
#      SPRING_JPA_HIBERNATE_DDL-AUTO: update
#      SPRING_APPLICATION_NAME: order-service
#      SPRINGDOC_SWAGGER-UI_PATH: /swagger-ui.html
